name = "redisapi"
compatibility_date = "2024-05-14"

[vars]
UPSTASH_REDIS_REST_TOKEN=AaYhAAIncDFiYTgxNThjYjkwZDI0NzlhYWRlYjUyNjFhOTZjOTg1YXAxNDI1Mjk 
UPSTASH_REDIS_REST_URL=https://grown-anteater-42529.upstash.io
